.travis.yml, package.json
Our builds were not able to deploy new versions to npm. Besides that, PRs generated two different build unnecessarily: one for the pr and other for the push.
This PR fixes theses behaviors.
=> Fix ci builds

.travis.yml
Add `before_deploy` script to run `yarn install`
We need to install dependencies on CI before deploying because we use `rimraf` lib on deploy process.
Without installing it, the deploy script will fail.
=> ci: add before_deploy script

src/components/Inputs/InputLabel.tsx, src/components/Inputs/TextInput.tsx, src/components/Inputs/__tests__/TextInput.test.tsx
Improves `TextInput` and `InputLabel` to update internal state when value passed by props changes.
The label wasn't animating to correct state when value passed by props changed.
- **TextInput**: adding an `useEffect` to "listen" when this prop change and update internal state
- **InputLabel**: adding `isEmpty` prop to existing `useEffect`
=> fix(TextInput): update state when value changes

src/components/Buttons/BaseButton.tsx, src/components/Buttons/__tests__/BaseButton.test.tsx
- calculate and set hitslop for small buttons
- to follow good UX practices and simplify access to small buttons
- using the onLayout prop to obtain the height and width of the button and calculate how much is left to meet the minimum requirements
[PRIM-666](https://produtomagnetis.atlassian.net/browse/PRIM-666)
[AST-7](https://produtomagnetis.atlassian.net/browse/AST-7)
=> [AST-7 | PRIM-666] fix(basebutton): min hitslop seted when button is smaller then 48

src/components/Inputs/InputErrorMessage.tsx, src/components/Inputs/InputEyeToggle.tsx, src/components/Inputs/TextInput.tsx, src/components/Inputs/__tests__/InputErrorMessage.test.tsx, src/components/Inputs/__tests__/TextInput.test.tsx
- Fix `TextInput`
- Fix problems raised after components implemented at `mobile-app`
- Fix `TextInput` erro message layout
- Add `hasError` and `hasFocus` to `InputEyeToggle` component
- Fix `TextInput` behavior when is `password` field
[AST-12](https://produtomagnetis.atlassian.net/browse/AST-12)
=> [AST-12] Fix text input error layout

CHANGELOG.md, package.json
* **basebutton:** min hitslop seted when button is smaller then 48 ([671a345](https://github.com/magnetis/astro-native/commit/671a3450f122ed013c539f1dcde1f5cbcf1225ef))
* **textinput:** fix text input error layout ([c2644fc](https://github.com/magnetis/astro-native/commit/c2644fcd5873df1d6466c96a49dffff1e3bb821a))
* **tabs:** add borderBottom option ([72f7e6a](https://github.com/magnetis/astro-native/commit/72f7e6aadc01cd35c244843a0abb74b5332298e2))
=> release: bump version to v1.4.0

src/components/ControlsToggles/Tabs.tsx, src/components/ControlsToggles/__tests__/Tabs.test.tsx
Fix tab item when single child container.
Before this fix, tab item was stretching to fill tab container.
Change item flex style from one to zero.
=> [AST-20] Fix Tab when has single item

.travis.yml, src/components/Buttons/Link.tsx, src/components/Buttons/__tests__/Link.test.tsx
- Fix link component
- The component was aligned vertically when nested inside another `Text` component
- Removed `Pressable` wrapper
Added color prop to component, basing on button color props (`'uranus' | 'earth' | 'venus' | 'mars'`)
| With Pressable | Without Pressable |
| ------------- |-------------| 
| <img src="https://user-images.githubusercontent.com/13890272/104501565-a8daf080-55be-11eb-99e5-3a3882a26b08.png" height="80" width="250" /> | <img src="https://user-images.githubusercontent.com/13890272/104501567-a9738700-55be-11eb-97f5-0c843a4012ef.png" height="80" width="250" /> |
[CH54268](https://app.clubhouse.io/magnetis/story/54268/corrigir-alinhamento-vertical-de-links-aninhados-em-componentes-de-texto)
=> [AST-9] Fix link component

src/components/Inputs/MaskedInput.tsx, src/components/Inputs/__tests__/MaskedInput.test.tsx
Fix `CurrencyInput` layout
The `CurrencyInput` renders useless and wrong spaces above and under input
Add validation to render the error message on `MaskedInput` (this is the base component of `CurrencyInput`)
Run the project, and test pass an error message at story book, needs to render default and error layout correctly
[AST-53](https://produtomagnetis.atlassian.net/browse/AST-53)
=> [AST-53] Fix currency input layout

commitlint.config.js
Add `release` type to commit lint config.
If that change wasn't made, would be impossible to run `npm version` without message lint giving error.
By copying [this example](https://github.com/conventional-changelog/commitlint/blob/master/@commitlint/config-conventional/index.js) and modifying where needed.
=> Add `release` type to commit lint config

src/components/Inputs/TextInput.tsx, src/components/Inputs/__tests__/TextInput.test.tsx
Fix `TextInput` type password
The `TextInput` type password not display `password manager` native from device
Only show `secureTextEntry` when `showPassword` is true.
https://user-images.githubusercontent.com/9031279/111193780-4dff4e80-8599-11eb-8800-8b56c595f2cf.mp4
[AST-61](https://produtomagnetis.atlassian.net/browse/AST-61)
=> [AST-61] Fix secure text entry to be true when input is password

src/components/Buttons/BaseButton.tsx, src/components/Icons/BaseIcon.tsx, src/components/Icons/__tests__/BaseIcon.test.tsx, src/components/Icons/stories/index.tsx, src/components/Icons/types.ts, src/components/__tests__/utils.test.ts, src/components/constants.ts, src/components/types.ts, src/components/utils.ts
Upgrade onPress prop to icon calculating hit slop when necessary
Add prop size to icon
To be easier to manipulate and be consistent with design system
Calculating histlop prop based on width and hight props (or size)
converting size prop to width and height
1. Run storybook locally, confirm hitSlop size with icon size lower than 48 and _onPress_ prop
2. Run storybook locally, confirm has no pressable area when icon doesn't have a _onPress_ prop
3. Run storybook locally, confirm icons width and height size when icon has a prop _size_
[AST-57](https://produtomagnetis.atlassian.net/browse/AST-57)
[AST-58](https://produtomagnetis.atlassian.net/browse/AST-58)
[PMF-155](https://produtomagnetis.atlassian.net/browse/PMF-155)
[PMF-156](https://produtomagnetis.atlassian.net/browse/PMF-156)
=> [AST-57] [AST-58] [PMF-156] [PMF-155] feat(baseicon): add pressable, hitslop and size prop into icon

src/components/ControlsToggles/Slider.tsx, src/components/ControlsToggles/__tests__/Slider.test.tsx, src/components/ControlsToggles/stories/Slider.story.tsx
Allow to hide slider label
We need to be able to use only the slider
Create a prop to do this
1. In this branch, go to control and toggles
2. Select the slider and mark the prop hideLabel
3. Verify if there is only the slider been displayed
=> feat(controls): allow to hide slider label

CHANGELOG.md
- **input** allow to hide slider label ([6997b09](https://github.com/magnetis/astro-native/commit/ea8c79281845c5cf28c5c0cf27400cc36b3e8dd0))
=> release: bump version to v1.8.1

src/components/ControlsToggles/Slider.tsx, src/components/ControlsToggles/__tests__/Slider.test.tsx, src/components/ControlsToggles/stories/Slider.story.tsx
Turns the slider label optional to be aligned to new prop `hideLabel` added in 6997b0974562193197c2d0ad89e816aabafbd2ba.
Also rename `hideLabel` to `hideHeader`
To avoid TypeScript errors when slider don't have a label and when prop `hideHeader` is true.
Remove requirement for label prop.
1. In this branch, go to control and toggles
2. Select the slider and mark the prop hideLabel
3. Don't include prop label
3. Verify if TypeScript doesn't show label related error
=> fix(slider): turns label optional

CHANGELOG.md, package.json
- **slider** improve type ([ad5f4f9](https://github.com/magnetis/astro-native/commit/ad5f4f9aa951ed4665aeb0292de36c1945b9661a)), show slider selected value without label ([5f6920a](https://github.com/magnetis/astro-native/commit/5f6920a9861a23068ba550831057c6581bd11d44)) and turns label optional ([ed2f2dd](https://github.com/magnetis/astro-native/commit/ed2f2dd2da056e1826fdaff379bcedcc7736020f))
=> release: bump version to v1.8.2

src/components/Buttons/__tests__/utils.test.tsx, src/components/Buttons/types.ts, src/components/Buttons/utils.ts
Add `moon` and `space` colors
Broaden the range of color possibilities
- Add `moon` (moon600) and `space` (moon100) colors
The unity test `src/components/Button/__tests__/utils` is enough to test this change
[AST-75](https://produtomagnetis.atlassian.net/browse/AST-75)
=> [AST-75] add new button colors

src/components/Inputs/InputLabel.tsx, src/components/Inputs/TextInput.tsx, src/components/Inputs/__tests__/InputLabel.test.tsx, src/components/Inputs/__tests__/TextAreaInput.test.tsx, src/components/Inputs/__tests__/TextInput.test.tsx
The current `TextInput` component layout obfuscates accessibility attributes. In e2e tests especially [XCUITest](https://appium.io/docs/en/drivers/ios-xcuitest/) in iOS can not locate pressable and touchables elements. 
Changing some properties and component layout of `TextInput` and `InputLabel` solves the problem without change any Astro visual style to these components.
e2e frameworks like Appium renders a tree of elements that represents native components. When a component enables `accessible` property  in React Native side any child element is hidden in generated tree of Appium. This breaks any test that needs to find this specific element.
The solution here only changes the component composition and do not change the `accessible` prop because is not necessary.
In this case of …
=> chore(TextInput): change component composition

src/components/ControlsToggles/Selection.tsx, src/components/ControlsToggles/__tests__/Selection.test.tsx, src/components/ControlsToggles/index.ts, src/components/ControlsToggles/stories/Selection.story.tsx, src/components/ControlsToggles/stories/index.ts
Add `Selection` component
Improve components base with a component that make easily select and option in a short list
- Create `Selection` component [`src/components/ControlsToggles/Selection`]
- Add story of component
Open storybook locally > Open ControlsToggles components list > Select `Selection` component
[AST-50](https://produtomagnetis.atlassian.net/browse/AST-50)
=> feat(controlstoggles/selection): add selection component

src/components/Buttons/BaseButton.tsx, src/components/Buttons/__tests__/BaseButton.test.tsx
When a button is loading, it should not be able to press it and trigger onPress event
Because loading state means that we are waiting for something before button interaction is avaliable.
Adding loading prop on disabled state of BaseButton.
N/A
1. Open any type of button;
2. Change loading prop to true;
3. Check that onPress event is no longer triggered;
=> Disable onPress event when loading is true

CHANGELOG.md, package.json
* **basebutton:** disable onPress event when loading is true ([798d2c1](https://github.com/magnetis/astro-native/commit/798d2c1989d8ef58b8ff0cf9bac35cc50813322d))
=> release: bump version to v1.8.7

src/components/Tabs/Tab.tsx, src/components/Tabs/TabsContainer.tsx, src/components/Tabs/index.ts, src/components/Tabs/stories/TabsContainer.story.tsx, src/index.ts
Add  rounded prop to render tabs with legacy layout
Turn the UI breaking change soft, changing the tab format
- Add `rounded` prop to render `circular` border radius
|Tabs |
| ------------- |
| https://user-images.githubusercontent.com/39625749/140752819-3c6884e6-220c-4e12-b103-97145e6083bd.png 
Select the tabs and check the border radius of tabs needs to turn rounded.
=> feat(tabs): add rounded prop

CHANGELOG.md, package.json
Bump version from 1.8.7 to 1.8.8
* **icons:** feat(icons): add icons ([9f3b7b9](https://github.com/magnetis/astro-native/commit/9f3b7b9567622f7b24732d31d9369e3911f716ef))
* Update dependabot.yml ([a98fb270](https://github.com/magnetis/astro-native/commit/a98fb2707316bed39a266aa96d7a36027c9efb24))
=> release: bump version from 1.8.7 to 1.8.8

CHANGELOG.md
* **icons:** fix(icons): fix star and star filled svg ([d3b206e](https://github.com/magnetis/astro-native/commit/d3b206e68bb2b78334c942c31481e0062080b784))
=> chore: bump version from v1.8.8 to v1.8.9

src/components/Buttons/__tests__/utils.test.tsx, src/components/Buttons/utils.ts
Fix button solid inversed text color
Select the button with type `inversed` and variant `solid`
=> fix(button): fix solid inversed text color

CHANGELOG.md, package.json
- **button:** fix solid inversed color ([b611886](https://github.com/magnetis/astro-native/commit/b611886971b375fd2f62cd2a71f6422cf1019378))
=> release: bump version to v2.0.0-next.3

CHANGELOG.md, package.json
- **buttonsgroup**: add contentContainerStyle and initialActiveItemIndex props ([60dc7a1](https://github.com/magnetis/astro-native/commit/60dc7a1788c55200c22be0387136585daa5cfc63))
=> chore: bump version to v2.0.0-next.4

src/components/Buttons/Button.tsx, src/components/Buttons/__tests__/utils.test.tsx, src/components/Buttons/utils.ts
Fix legacy buttons when using outline or ghost types
Because it's broken, render with wrong colors.
Change colors in legacy variant.
https://user-images.githubusercontent.com/1580205/155006821-4bfcfb16-b309-4072-ad85-dc50132bf367.mp4
1. Run storybook;
2. Run astro-native app;
3. In button, change to legacy variant;
4. Also in button, change to outline and ghost types;
=> [AST-164] Fix legacy variant layout for outline and ghost button types

yarn.lock
Fix vulnerabilities `CVE-2022-0144` and `CWE-269`
=> chore: update shelljs to version 0.8.5

package.json, yarn.lock
Update refractor for main branch
- fix [Cross-Site Scripting](https://github.com/magnetis/astro-native/security/dependabot/1)
- fix [Denial of service](https://github.com/magnetis/astro-native/security/dependabot/6)
- fix [ReDoS in Prism](https://github.com/magnetis/astro-native/security/dependabot/17)
- fix [ReDoS in prismjs](https://github.com/magnetis/astro-native/security/dependabot/24)
- fix [Cross-site Scripting](https://github.com/magnetis/astro-native/security/dependabot/36)
- update caniuse-lite database to fix warning during tests
=> [AST-174] Update refractor to fix prismjs vulnerabilities

package.json, yarn.lock
Update refractor for astro-native@next
- fix [Cross-Site Scripting](https://github.com/magnetis/astro-native/security/dependabot/1)
- fix [Denial of service](https://github.com/magnetis/astro-native/security/dependabot/6)
- fix [ReDoS in Prism](https://github.com/magnetis/astro-native/security/dependabot/17)
- fix [ReDoS in prismjs](https://github.com/magnetis/astro-native/security/dependabot/24)
- fix [Cross-site Scripting](https://github.com/magnetis/astro-native/security/dependabot/36)
- update caniuse-lite database to fix warning during tests
=> [AST-175] Update refractor to fix prismjs vulnerabilities

src/components/Buttons/__tests__/utils.test.tsx, src/components/Buttons/utils.ts
Changing some tokens that were not updated
It is necessary to ensure that all variants and styles of controls must be available to be used when applying the component.
Comparing figma tokens doc with properties and changing what was needed
=> Updated tokens in getButtonProperties

ios/Podfile, src/components/Buttons/BaseButton.tsx, src/components/Buttons/__tests__/BaseButton.test.tsx, src/components/Buttons/stories/GhostIconButton.story.tsx, src/components/Buttons/stories/GhostIconLabelButton.story.tsx, src/components/Buttons/stories/IconButton.story.tsx, src/components/Buttons/stories/IconLabelButton.story.tsx, src/components/Buttons/stories/OutlineButton.story.tsx, src/components/Buttons/stories/OutlineIconButton.story.tsx, src/components/Buttons/stories/OutlineIconLabelButton.story.tsx, src/components/Buttons/stories/PrimaryButton.story.tsx, src/components/Buttons/types.ts, storybook/options.ts
(in main)
Improve the visual feedback given to the user when he presses the button
To improve the accessibility of the application. When the buttons are clicked return the action was done.
- Added pressed functionality in Presseble passing default opacity 0.7
- Added `use_flipper` to fix error in build
https://user-images.githubusercontent.com/44146877/162795924-016d7d3a-1904-4a0b-aa25-49d9c32e7686.mov
=> Add Button pressed feedback

CHANGELOG.md, package.json
* refactor(stories): added opacity in stories of buttons and removed some props already defined ([28de5f3](https://github.com/magnetis/astro-native/commit/28de5f39c8dfefe80f4e6217a358240c0df840df))
* refactor(podfile): added code to enables flipper ([b705997](https://github.com/magnetis/astro-native/commit/b7059973bdeb8af16ee439e4cc2cddced376e807))
* refactor(button): add pressed feedback and opacity prop ([c9cda43](https://github.com/magnetis/astro-native/commit/c9cda43c3482b95dc66e40a2aa87c9f643278a74))
* chore: fix changelog ([0b81132](https://github.com/magnetis/astro-native/commit/0b8113282ed89d183ebf8ac6e5f010f3e888ad1a))
=> chore: bump version from v1.8.9 to v1.9.0

CHANGELOG.md, package.json
* feat(button): add pressed feedback and opacity prop ([e8b22ad](https://github.com/magnetis/astro-native/commit/e8b22ad95bbf9af0cb0a0b046a3f28c4bc71982b))
* refactor(utils): fixed token in getButtonProperties ([b5fa2e1](https://github.com/magnetis/astro-native/commit/b5fa2e1dc7fbfb690c152b00c261669fe91da6da))
=> chore: bump version to v2.0.0-next.5 to v2.0.0-next.6

CHANGELOG.md
* ci(gh-action): implement gh-action flow for tests and publish new version ([788c478](https://github.com/magnetis/astro-native/commit/788c47867664e91f54dd04f5c6c1a6327c3b5471))
* test(jest-config): ignore index and types files on tests ([7700da3](https://github.com/magnetis/astro-native/commit/7700da36e26f35bf10a70a0383da10b2ecf89724))
* refactor(icons): added arrows icon ([fc859d3](https://github.com/magnetis/astro-native/commit/fc859d374c87d63360c5e5bbb6012d65e51d03ed))
* refactor(jest.config): /Arros in collectCoverageFrom ([35d312e](https://github.com/magnetis/astro-native/commit/35d312eeca6fd7d9f175f7814aacc3cfec606352))
* refactor(icons): add getViewBox() and getSize() to viewBox and width/height ([a0f154d](https://github.com/magnetis/astro-native/commit/a0f154d14bacdf17f7d623d18a08 …
=> chore: bump version to v2.0.0-next.6 to v2.0.0-next.7

CHANGELOG.md
* refactor(icons): added informations icons ([a1fca4b](https://github.com/magnetis/astro-native/commit/a1fca4be2cf52929712579e9a2bba4d562a6a0dc))
* refactor(jest.config): /Information in collectCoverageFrom ([3becc08](https://github.com/magnetis/astro-native/commit/3becc08e3de786b1cbd8fea8f3e18f2cc47f0bc0))
* refactor(icons): separating the imports of modules from the relatives ([7ccc20d](https://github.com/magnetis/astro-native/commit/7ccc20d5a08dcdc331d1259ff766d92092156324))
* refactor(icons): added essencials icons ([66c74cc](https://github.com/magnetis/astro-native/commit/66c74cc2469d0f746d6ecba75d6afe26b19ff69d))
* refactor(icons): added documents icon ([834ac5b](https://github.com/magnetis/astro-native/commit/834ac5b8cc52bfff6f2ff3f23513677d9774293c))
* refactor(icons): added …
=> chore(release): bump version from v2.0.0-next.7 to v2.0.0-next.8

CHANGELOG.md, package.json
* refactor(icons): added informations icons ([a1fca4b](https://github.com/magnetis/astro-native/commit/a1fca4be2cf52929712579e9a2bba4d562a6a0dc))
* refactor(jest.config): /Information in collectCoverageFrom ([3becc08](https://github.com/magnetis/astro-native/commit/3becc08e3de786b1cbd8fea8f3e18f2cc47f0bc0))
* refactor(icons): separating the imports of modules from the relatives ([7ccc20d](https://github.com/magnetis/astro-native/commit/7ccc20d5a08dcdc331d1259ff766d92092156324))
* refactor(icons): added essencials icons ([66c74cc](https://github.com/magnetis/astro-native/commit/66c74cc2469d0f746d6ecba75d6afe26b19ff69d))
* refactor(icons): added documents icon ([834ac5b](https://github.com/magnetis/astro-native/commit/834ac5b8cc52bfff6f2ff3f23513677d9774293c))
* refactor(icons): added …
=> chore: bump version from v2.0.0-next.6 to v2.0.0-next.7

.github/dependabot.yml
Set frontend team to dependabot reviewers. [Documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers)
=> chore(dependabot): update dependabot.yml

src/components/Buttons/Button.tsx, src/components/ButtonsGroup/ButtonsGroup.tsx, src/components/ButtonsGroup/__tests__/ButtonsGroup.test.tsx, src/components/ButtonsGroup/stories/ButtonsGroup.story.tsx
Updates ButtonsGroup to receive props `active` and `inactive` as default props.
Following the needs to optimize our components.
- Add `active` and `inactive` props to ButtonGroups to load by default:
- Deprecate `inverted` and `legacy` props;
- Correct the `ButtonGroupProps` types;
- Delete function `getButtonGroupVariant`;
- Use `type` and `variant` properties according to whether the button is active or not;
- Fix unit tests;
1. Start storybook with `yarn storybook`;
2. Run your preferred simulator;
4. In the storybook page, choose `Buttons Group` in `Buttons Group`;
5. See if `ActiveType`, `ActiveVariant`, `InactiveType` and `InactiveVariant` props are working correctly;
[CONFIA-678](https://produtomagnetis.atlassian.net/browse/CONFIA-678)
[CONFIA-678]: …
=> feat(ButtonsGroup): update ButtonsGroup to receive props active inactive as default props [CONFIA-678]

CHANGELOG.md, package.json
* **buttons-group:** transfer buttons group props to items ([32832b4](https://github.com/magnetis/astro-native/commit/32832b4abe2011c940d76f2395c2f8ec8ccf1970))
* **ButtonsGroup:** add flexDirection to container ([#674](https://github.com/magnetis/astro-native/issues/674)) ([95bfd23](https://github.com/magnetis/astro-native/commit/95bfd23a3fb9163ef00d96988f71f6ee029a1751))
* **buttons-group:** rename onPressItem prop ([19f37ea](https://github.com/magnetis/astro-native/commit/19f37ea96f601a5e7e5a39178f43c042f1574dc5)), closes [#622](https://github.com/magnetis/astro-native/issues/622)
* **ButtonsGroup:** update ButtonsGroup to receive props active inactive as default props [CONFIA-678] ([#673](https://github.com/magnetis/astro-native/issues/673)) …
=> chore: bump version from v2.0.0-next.7 to v2.0.0-next.8

ios/Podfile.lock, jest.config.js, package.json, src/components/ButtonsGroup/ButtonsGroup.tsx, yarn.lock
Update ButtonsGroup component properties
So that can be used in nested lists.
1. Installing `react-native-gesture-handler`;
2. Using `react-native-gesture-handler` FlatList component instead of `react-native` FlatList;
3. Adding the optional property `listKey` to the `ButtonsGroup` component .
N/A
1.  Run `yarn storybook` and run the project in your preferred emulator;
2. On the side bar, choose ButtonsGroup;
3. Check if it's working correctly.
[CONFIA-816](https://https://produtomagnetis.atlassian.net/browse/CONFIA-816)
[CONFIA-816]: https://produtomagnetis.atlassian.net/browse/CONFIA-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ButtounsGroup): update ButtonsGroup component [CONFIA-816]

CHANGELOG.md, package.json
* **fonts:** make fontWeight and fontStyle style props work for fonts ([#691](https://github.com/magnetis/astro-native/issues/691)) ([d722b87](https://github.com/magnetis/astro-native/commit/d722b87b8feff95df6391f198a16a385e903b985))
* **svg:** fix svg path in icon components ([#685](https://github.com/magnetis/astro-native/issues/685)) ([376ed56](https://github.com/magnetis/astro-native/commit/376ed565d95937343348b3509007b31c621a37ee))
* **ButtounsGroup:** update ButtonsGroup component [CONFIA-816] ([#687](https://github.com/magnetis/astro-native/issues/687)) ([6b577f8](https://github.com/magnetis/astro-native/commit/6b577f8da44b62b957c702cc28f3e33ba113eb7b))
[CONFIA-836](https://produtomagnetis.atlassian.net/browse/CONFIA-836)
[CONFIA-816]: …
=> release: bump version from v2.0.0-next.8 to v2.0.0-next.9

src/components/Buttons/Link.tsx, src/components/Buttons/__tests__/Link.test.tsx, src/components/Buttons/stories/Link.story.tsx, src/components/Buttons/utils.ts
Use any color in Link component.
To fix layout issues when using Link without new color tokens.
- Changed getButtonMainColor function to return color if doesn't match legacy color tokens.
https://github.com/magnetis/astro-native/assets/1580205/e01a8314-d2d2-472b-b7f0-21c4fc816201
- Run yarn start
- Run storybook
- Open Android and iOS simulators
- Choose Link component in storybook
- Try several color names and codes like `red`, `yellow`, `#306090` and other ones
[CONFIA-1202](https://produtomagnetis.atlassian.net/browse/CONFIA-1202)
[CONFIA-1202]: https://produtomagnetis.atlassian.net/browse/CONFIA-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(link): allow use any color

ios/AstroNative.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, src/components/Text/BaseText.tsx, src/components/Text/PrimaryText.tsx, yarn.lock
Configure iOS to v11, remove outdated maintainers info, update browserslist database and fix typo in PrymaryText component internal name
To release version 1.11.0
- Configure iOS to v11,
- Remove outdated maintainers info
- Update browserslist database
- Fix typo in PrymaryText component internal nbame
Checkout branch and run in different terminal panels:
- `yarn`
- `yarn start`
- `yarn storybook`
- `yarn android`
- `yarn ios` (now can be run in the same terminal without rosetta)
=> chore: prepare for release v1.11.0

package.json, yarn.lock
Update `commitizen` package from version 4.2.4 to 4.3.0.
To update its transitive dependency `minimist` to version 1.2.7, removing the vulnerability `Prototype Pollution` described in https://github.com/magnetis/astro-native/security/dependabot/82.
Updated `commitizen` package from version 4.2.4 to 4.3.0.
[N/A]
[CONFIA-1278](https://produtomagnetis.atlassian.net/browse/CONFIA-1278)
[CONFIA-1278]: https://produtomagnetis.atlassian.net/browse/CONFIA-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(commitizen): update commitizen library to 4.3.0 in astro-native [CONFIA-1278]

package.json, yarn.lock
Update `commitizen` package from version 4.2.4 to 4.3.0 of astro-native next.
To update its transitive dependency `minimist` to version 1.2.7, removing the vulnerability `Prototype Pollution` described in https://github.com/magnetis/astro-native/security/dependabot/82.
Updated `commitizen` package from version 4.2.4 to 4.3.0.
[N/A]
[CONFIA-1279](https://produtomagnetis.atlassian.net/browse/CONFIA-1279)
[CONFIA-1279]: https://produtomagnetis.atlassian.net/browse/CONFIA-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(commitizen): update commitizen library to 4.3.0 in astro-native-next [CONFIA-1279]

CHANGELOG.md, package.json
* chore(deps): bump qs from 6.5.2 to 6.5.3 [CONFIA-1088] ([#708](https://github.com/magnetis/astro-native/issues/708))([67b60f1](https://github.com/magnetis/astro-native/commit/67b60f1))
* chore(deps): remove unused library concurrently ([#713](https://github.com/magnetis/astro-native/issues/713))([47612ca](https://github.com/magnetis/astro-native/commit/47612ca))
* chore(deps): bump @sideway/formula from 3.0.0 to 3.0.1 ([#718](https://github.com/magnetis/astro-native/issues/718))([3de72e2](https://github.com/magnetis/astro-native/commit/3de72e2))
* chore(react-native): update react native to 0.67.5 [CONFIA-1214] of astro-native-next ([#721](https://github.com/magnetis/astro-native/issues/721))([ca983bb](https://github.com/magnetis/astro-native/commit/ca983bb))
* chore(deps-dev): bump …
=> chore: bump version to v2.0.0-next.11

.github/workflows/publish.yml, .github/workflows/pull-requests.yml
Update node version from 14 to 16 on Github Actions Workflows.
To run Node from the default version, 16, and fix the following error:
`error cosmiconfig-typescript-loader@5.0.0: The engine "node" is incompatible with this module. Expected version ">=v16". Got "14.21.3"`
Updating Node version on `.github/workflows/publish.yml`;
Updating Node version on `.github/workflows/pull-requests.yml`;
=> chore: bump node version from 14 to 16

package.json, yarn.lock
Bump `codecov` version from 3.8.1 to 3.8.3.
To fix `TypeError: Cannot read property 'startsWith' of undefined` on Github Actions as suggested in https://github.com/codecov/codecov-node/issues/324 thread.
Updating the version of `codecov` in `package.json` and `yarn.lock`
=> chore(dev-deps): bump codecov version from 3.8.1 to 3.8.3

jest.config.js, src/components/Tags/Tag.tsx, src/components/Tags/__tests___/Tag.test.tsx, src/components/Tags/__tests___/utils.test.tsx, src/components/Tags/constants.ts, src/components/Tags/index.ts, src/components/Tags/stories/Tag.story.tsx, src/components/Tags/stories/index.ts, src/components/Tags/types.ts, src/components/Tags/utils.ts, src/index.ts, storybook/stories.ts
To create `Tag` component on astro-native@next.
To follow our Design System, having our components gathered in one place that can be used in different projects.
1. Creating the tag component;
2. Adding tag story to be manipulated in the storybook.
https://github.com/magnetis/astro-native/assets/52300436/3213ffcb-5327-4108-ad6b-396d76692a6c
- Pull the branch and run `yarn start` and `yarn storybook`;
- Run your preferred emulator;
- In the storybook, choose `Tags` option in the side bar menu;
- Change the properties and see if it changes in the emulator. 
[CONFIA-1335](https://produtomagnetis.atlassian.net/browse/CONFIA-1335)
[CONFIA-1335]: https://produtomagnetis.atlassian.net/browse/CONFIA-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(components): create tag component on astro-native@next [CONFIA-1335]

CHANGELOG.md, package.json
* **components:** add divider component in astro-native-next [CONFIA-1337] ([#782](https://github.com/magnetis/astro-native/issues/782)) ([6baef63](https://github.com/magnetis/astro-native/commit/6baef6384699ee0d96fcbaf33ffe2bd1542f9ff1))
* **components:** create tag component on astro-native@next [CONFIA-1335] ([#791](https://github.com/magnetis/astro-native/issues/791)) ([0f13a14](https://github.com/magnetis/astro-native/commit/0f13a14caf608c97084747e8ff71f4da7bf4738d))
[CONFIA-1337]: https://produtomagnetis.atlassian.net/browse/CONFIA-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CONFIA-1335]: https://produtomagnetis.atlassian.net/browse/CONFIA-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> chore: bump version to v2.0.0-next.12

CHANGELOG.md, package.json
- chore(dev-deps): bump codecov version from 3.8.1 to 3.8.3 [96d115f](https://github.com/magnetis/astro-native/commit/96d115f3a251cf07c964ac8e09297f23e3ae9b67)
- chore(deps): bump react-native-svg from 12.5.0 to 13.11.0 [e6ea5ba](https://github.com/magnetis/astro-native/commit/e6ea5baa8397ca55675e85161f9ad573dddb25d5)
=> chore: bump astro-native to v1.11.1

ios/AstroNative.xcodeproj/project.pbxproj, package.json
Makes project compatilbe with NodeJS 20
Current NodeJS version that we use has reached end of life, what means that it will not receive updates and fixes anymore.
So, we move to NodeJS 20 and fix the project to works with it.
Set openssl-legacy-provider node option env var in storybook command.
1. Checkout the branch, remove `node_modules` folder and install dependencies with `yarn`
2. Start packager with `yarn start`
3. Start storybook with `yarn storybook`
4. Run app in both platforms (Android and iOS)
=> fix: Node 20 compatibility in main branch [CONFIA-1418]

package.json
Makes project compatilbe with NodeJS 20
Current NodeJS version that we use has reached end of life, what means that it will not receive updates and fixes anymore.
So, we move to NodeJS 20 and fix the project to works with it.
Set openssl-legacy-provider node option env var in start and storybook commands.
1. Checkout the branch, remove `node_modules` folder and install dependencies with `yarn`
2. Start packager with `yarn start`
3. Start storybook with `yarn storybook`
4. Run app in both platforms (Android and iOS)
=> fix: Node 20 compatibility in next branch [CONFIA-1419]

CHANGELOG.md, package.json
* node 20 compatibility ([#830](https://github.com/magnetis/astro-native/issues/830)) ([de0acf8](https://github.com/magnetis/astro-native/commit/de0acf82f8f2e34b1412be9d884aa7f75135f6c6))
=> chore: bump version to v2.0.0-next.13

.github/workflows/publish.yml, .github/workflows/pull-requests.yml, .husky/commit-msg, .husky/pre-commit, package.json, yarn.lock
Updates husky to version 9.0.7
Better api, smaller size and to reduces the chance of having vulnerabilities in dependencies.
Also fix node version in github actions workflows files.
=> chore(deps-dev): bump husky from 7.0.1 to 9.0.7 [CONFIA-1644]
