package.json
src/components/Buttons/BaseButtonText.tsx
src/components/Buttons/BaseText.tsx
src/components/Buttons/GhostIconLabelButton.tsx
src/components/Buttons/IconLabelButton.tsx
src/components/Buttons/OutlineButton.tsx
src/components/Buttons/OutlineIconLabelButton.tsx
src/components/Buttons/PrimaryButton.tsx
src/components/Buttons/__tests__/BaseButtonText.test.tsx
src/components/Buttons/__tests__/GhostIconLabelButton.test.tsx
src/components/Buttons/__tests__/IconLabelButton.test.tsx
src/components/Buttons/__tests__/OutlineButton.test.tsx
src/components/Buttons/__tests__/OutlineIconLabelButton.test.tsx
src/components/Buttons/__tests__/PrimaryButton.test.tsx
src/components/Buttons/index.ts
src/components/Buttons/utils.ts
yarn.lock

This PR aims on removing any use of styled-components from the project with the goal of turning the package more lightweight on final bundle.

Remove styled components

---

lint-staged.config.js
package.json
yarn.lock

Add precommit and prepush hooks
To run linters and related tests in every commit and run `yarn ci` on prepush

Configure precommit and prepush hooks

---

src/components/Inputs/ControlInput.tsx
src/components/Inputs/TextInput.tsx
src/components/Inputs/__tests__/ControlInput.test.tsx
src/components/Inputs/__tests__/utils.test.ts
src/components/Inputs/index.ts
src/components/Inputs/utils.ts
src/stories/Inputs.stories.tsx

Implement ControlInput

---

.travis.yml
src/components/Inputs/ControlInput.tsx
src/components/Inputs/MaskedInput.tsx
src/components/Inputs/TextInput.tsx
src/components/Inputs/types.ts

Write JSDOC for input components
To provide an accessible documentation inside code editors.

Write Input docs

---

src/components/Buttons/BaseButton.tsx
src/components/Buttons/BaseButtonText.tsx
src/components/Buttons/GhostIconButton.tsx
src/components/Buttons/GhostIconLabelButton.tsx
src/components/Buttons/IconButton.tsx
src/components/Buttons/IconLabelButton.tsx
src/components/Buttons/IconLinkButton.tsx
src/components/Buttons/Link.tsx
src/components/Buttons/OutlineButton.tsx
src/components/Buttons/OutlineIconButton.tsx
src/components/Buttons/OutlineIconLabelButton.tsx
src/components/Buttons/PrimaryButton.tsx
src/components/Buttons/__tests__/BaseButton.test.tsx
src/components/Buttons/__tests__/GhostIconButton.test.tsx
src/components/Buttons/__tests__/GhostIconLabelButton.test.tsx
src/components/Buttons/__tests__/IconButton.test.tsx
src/components/Buttons/__tests__/IconLabelButton.test.tsx
src/components/Buttons/__tests__/IconLinkButton.test.tsx
src/components/Buttons/__tests__/OutlineButton.test.tsx
src/components/Buttons/__tests__/OutlineIconButton.test.tsx
src/components/Buttons/__tests__/OutlineIconLabelButton.test.tsx
src/components/Buttons/__tests__/PrimaryButton.test.tsx
src/components/Buttons/types.ts
src/components/Buttons/utils.ts
src/stories/Buttons.stories.tsx

Write JSDOC for buttons components

Write Buttons docs

---

src/components/Buttons/IconLinkButton.tsx
src/components/Buttons/types.ts
src/components/ControlsToggles/Checkbox.tsx
src/components/ControlsToggles/Radio.tsx
src/components/ControlsToggles/RadioGroup.tsx
src/components/ControlsToggles/Slider.tsx
src/components/ControlsToggles/Tabs.tsx
src/components/ControlsToggles/Toggle.tsx
src/components/ControlsToggles/__tests__/Checkbox.test.tsx
src/components/ControlsToggles/__tests__/Radio.test.tsx
src/components/ControlsToggles/__tests__/RadioGroup.test.tsx
src/components/ControlsToggles/__tests__/Slider.test.tsx
src/components/ControlsToggles/__tests__/Toggle.test.tsx
src/components/ControlsToggles/__tests__/utils.test.ts
src/components/ControlsToggles/types.ts
src/components/Inputs/types.ts
src/components/Inputs/utils.ts
src/components/Text/utils.ts
src/stories/ControlsToggles.stories.tsx

Write JSDoc for Controls&Toggles
*Bonus*:
* Write JSDoc for text utils function;
* Write JSDoc for buttons utils functions;
* Change prop names to match project pattern in Controls&Toggles;
* Add default value on JSDoc of Buttons and Inputs;

Write docs for Controls & Toggles

---

.travis.yml

Change Travis CI config file to build and deploy on new tags release.

chore(ci): Make travisci deploy occur on tags only

---

src/components/Inputs/ControlInput.tsx
src/components/Inputs/MaskedInput.tsx
src/components/Inputs/TextInput.tsx

Change testID prop forward to input component instead of container view.
To be able to test components usage outside Astro Native project.

fix(Inputs): change testID prop forward

---

CHANGELOG.md
package.json

* **Buttons:** Allow button text to wrap lines ([756cd70](https://github.com/magnetis/astro-native/commit/756cd708f19b40cd1c14d008f02e37ee2b3b428b))
* **InputEyeToggle:** change icon background color ([686cde4](https://github.com/magnetis/astro-native/commit/686cde43653acf4fb23a01106829e9ca62126034))
* **Inputs:** change testID prop forward ([d8f21e7](https://github.com/magnetis/astro-native/commit/d8f21e7e103d27ec6ef97115197304ca4cab9387))
* **MaskedInput:** show textAlign as left always ([767f7c6](https://github.com/magnetis/astro-native/commit/767f7c6f7d1726f2a7453bf2b308ed641e8bf0e4))
* **TextInput:** fix password eye toggle behavior ([364bda5](https://github.com/magnetis/astro-native/commit/364bda521af2d598ea5183643b14c4f9bef4681a))

release: bump version to v1.0.1

---

tsconfig.json

Since CommonJS has problems with React

Change tsconfig module to ES2015

---

CHANGELOG.md
package.json

* **Buttons:** change isDisabled prop to `disabled` ([8ea62a0](https://github.com/magnetis/astro-native/commit/8ea62a0276fee107f8761f683a7e4aec42268b11))
* **Buttons:** change isLoading prop to `loading` ([c8c6ed1](https://github.com/magnetis/astro-native/commit/c8c6ed1f2506636ca9aa3dd7882feb655deca0da))
* **Checkbox:** change isIndeterminate props to `indeterminate` ([20e0224](https://github.com/magnetis/astro-native/commit/20e0224a15b6b1d9a763dd0782db6450803ed3f9))
* **ControlInput:** forward testID prop to input component ([6a24b6a](https://github.com/magnetis/astro-native/commit/6a24b6a85d66ab98f51ac1f2d7e7fc73595a5b89))
* **Controls&Toggles:** change isDisabled prop to `disabled` ([7e5a08b](https://github.com/magnetis/astro-native/commit/7e5a08b99c8aedcf807191dfe5d1feb7ca9871f6))
* …

release: bump version to v1.0.3

---

CHANGELOG.md
package.json

* **ControlInput:** fix format bevahior ([2b3fbc4](https://github.com/magnetis/astro-native/commit/2b3fbc461f2c784573299e9c18ce79c9a4ca2f79))
* **Inputs:** Implement Currency Input ([c732d0a](https://github.com/magnetis/astro-native/commit/c732d0a36b640754c589b20253d982f47c5a2b8b))

release: bump version to v1.1.0

---

.travis.yml

It was throwing an error since `rimraf` package was not installed

chore(ci): Fix deploy stage

---

src/components/Inputs/CurrencyInput.tsx
src/components/Inputs/__tests__/CurrencyInput.test.tsx

Implement controlled input support for CurrencyInput

feat(CurrencyInput): Implement controlled input support

---

CHANGELOG.md
package.json

* **CurrencyInput:** Implement controlled input support ([1d27f5c](https://github.com/magnetis/astro-native/commit/1d27f5c8edfb1251a58b4cf56de66456c2e8f663))

release: bump version to v1.2.0

---

src/components/Text/Title.tsx
src/components/Text/__tests__/Title.test.tsx
src/components/Text/index.ts
src/components/Text/stories/Title.story.tsx
src/components/Text/stories/index.ts

Add Title component
Title component was the last missing typography

feat(Title): Implement Title component

---

package.json
src/components/Inputs/TextInput.tsx
src/components/Inputs/__tests__/TextInput.test.tsx

Fix text input label animation
When a input starts with value, the label doesn't animate correctly
Considering the value in animation rule

fix(TextInput): fix input text label animation

---

CHANGELOG.md
package.json

* **TextInput:** fix input text label animation ([9d0b667](https://github.com/magnetis/astro-native/commit/9d0b667c6d520bdfa3d24e3729bc71182db4c54d))
* **Title:** Implement Title component ([f2b242f](https://github.com/magnetis/astro-native/commit/f2b242fce8118fd3c5773a58481edbe3fc7263c6))

release: bump version to v1.3.0

---

CHANGELOG.md
package.json

* **TextInput:** update state when value changes ([a0b2d74](https://github.com/magnetis/astro-native/commit/a0b2d74e5ff808462651207ea1a6e4aede7df1a3))

release: bump version to v1.3.1

---

.github/CONTRIBUTING.md

Write contributing guide for project.

docs: Write Contributing Guide

---

.github/CONTRIBUTING.md
commitlint.config.js
package.json
yarn.lock

Add [Commitizen](https://github.com/commitizen/cz-cli) and [CommitLint](https://github.com/conventional-changelog/commitlint) to assure commit message patterns are being followed.
[ch53863](https://app.clubhouse.io/magnetis/story/53863/adicionar-commitlint-e-commitzen-no-projeto)

Add Commitizen and  CommitLint

---

.github/PULL_REQUEST_TEMPLATE.md

To update pr template
In order to make more sense for the current context of our lib.
We should update the pr template file.
Open a pr and verify if the template is correct.
[AST-11](https://produtomagnetis.atlassian.net/browse/AST-11)

[AST-11] Update pr template

---

CHANGELOG.md
package.json

* **checkicon:** fix check icon view box ([1fc2cf3](https://github.com/magnetis/astro-native/commit/1fc2cf3e8939f0778fdd392767a6a2ea27761a36))
* **flagicon:** update FlagIcon to match DS definition ([d802668](https://github.com/magnetis/astro-native/commit/d802668e81f8a2315e4b133b54ebef2d2e83a95f))
* **icons:** fix fillRule and clipRulle misspelling on several icons ([2c0093b](https://github.com/magnetis/astro-native/commit/2c0093bd2509ef012987781638e8df8034717621))
* **link:** fix vertical alignment ([8de6696](https://github.com/magnetis/astro-native/commit/8de669615be3b41671ee996e3f5050fd98aefaaf))
* **maskedinput:** fix masked input error layout ([0af9e14](https://github.com/magnetis/astro-native/commit/0af9e14ef79186c9e8115bc3f0e1ddbbada107c2))
* **tabs:** fix UI when has single item …

release: bump version to v1.5.0

---

.travis.yml

Update secure api_token for deploy script in order to fix automatic deploy
[AST-55](https://produtomagnetis.atlassian.net/browse/AST-55)

[AST-55] Update secure api_token for deploy script

---

CHANGELOG.md
package.json

* **textinput:** fix secure text entry to be true when input is password ([3e10f5c](https://github.com/magnetis/astro-native/commit/3e10f5c26a237d201601cf4d31263d5298af757c))
* **tabs:** add alignment options ([a18c276](https://github.com/magnetis/astro-native/commit/a18c276b00633dad9463de17fbdc78da1d724cb3))
[AST-63](https://produtomagnetis.atlassian.net/browse/AST-63)

[AST-63] release: bump version to v1.6.0

---

CHANGELOG.md
package.json

* **icon:** add camera, notification and pause icons ([56639ad](https://github.com/magnetis/astro-native/commit/56639ad52209721eaff8924b3f6cf17449e1d13a))
* **icon:** add pressable, calculate hitslop and add props size and onPress into icon ([dde028b](https://github.com/magnetis/astro-native/commit/dde028bb255d2e7d0a10f3e72e04b43b05a548a0))

release: bump version to v1.7.0

---

.dependabot/config.yml
package.json
yarn.lock

Add dependabot list fo prs, and update y18n dependecy due to a vulnerability.
[AST-73](https://produtomagnetis.atlassian.net/browse/AST-73)

Update dependabot and dependcies

---

CHANGELOG.md
package.json

* **input** add text area ([c018b39](https://github.com/magnetis/astro-native/commit/0bd590d29915900f126b35fdbe023a66f3ae2a96))

release: bump version to v1.8.0

---

.github/CONTRIBUTING.md

Fix contributing guide typos
Fix typos through the text
N/A
N/A
N/A

docs(contributing): fix typos

---

package.json

Update package version for release

release: update package version to v1.8.1

---

src/components/ControlsToggles/Slider.tsx

Add props to slider interface to prevent errors when using  images for customizing the slider

feat(slider): improve type

---

src/components/Inputs/ControlInput.tsx

Fix control input buttons positioning
* Go to this branch
* Check if control input's button is not cut by the label.

fix(input/control): fix buttons position

---

CHANGELOG.md
package.json

- **input** fix control buttons position ([173ebd5](https://github.com/magnetis/astro-native/commit/173ebd58a2605b27b5778236bb57b4ac91cb5e66))
- **buttons**: add moon and space colors ([d68b355](https://github.com/magnetis/astro-native/commit/d68b35565893200a543c59c43f6ccbf024b377cb))

release: bump version to v1.8.3

---

CHANGELOG.md
package.json

- **input** change input control to focus on input when clicking the buttons  ([173ebd5](https://github.com/magnetis/astro-native/commit/8d35bbe570502dcf01ca10cb0af1e471e69d1123))

release: bump version to v1.8.4

---

CHANGELOG.md
package.json

- **input** change component composition to be compatible with Appium ([606276c](https://github.com/magnetis/astro-native/commit/606276ce78f76f920adbb307966446021f46e821))

release: bump version to v1.8.5

---

package.json
yarn.lock

Resolve "Regular Expression Denial of Service in postcss"
Related: #166

[AHA-216] chore(deps): [security] bump postcss from 7.0.35 to 7.0.36

---

CHANGELOG.md
package.json

- **component**: add new selection component ([415616f](https://github.com/magnetis/astro-native/commit/415616f05220e5278073670623e3f64f9c7ab359))
- **icon**: add new RotatePhone icon ([70dd269](https://github.com/magnetis/astro-native/commit/70dd269c4aa545f5f260d5a972d4cb7156219581))

release: bump version to v1.8.6

---

.github/workflows/publish.yml
.github/workflows/pull-requests.yml

Implement CI scripts to use Github Actions.

Implement CI scripts for Github Actions

---

ios/AstroNative.xcodeproj/project.pbxproj
ios/Podfile
ios/Podfile.lock
src/components/Buttons/types.ts
src/components/ButtonsGroup/ButtonsGroup.tsx
src/components/ButtonsGroup/__tests__/ButtonsGroup.test.tsx
src/components/ButtonsGroup/stories/ButtonsGroup.story.tsx
src/components/ButtonsGroup/stories/index.ts
storybook/stories.ts

Create buttons group
To be used on screens that have filters
A parent component was created, which is the list, and within it there are children that represent each item in the list.
https://user-images.githubusercontent.com/24248893/135153542-3458b13e-da6e-40d2-89d9-30fee491fbe2.mp4
Run application locally and test the following:
- onPress function should be called and should change background color when item is active

feat(buttons-group): create buttons group

---

CHANGELOG.md
package.json

* **tabs:** add rounded prop ([234e6cf](https://github.com/magnetis/astro-native/commit/234e6cf98e0c23f13dc994e52251ec30706ddec3))

release: bump version to v2.0.0-next.2

---

package.json

Enable husky and pre-commit hook
Better commit messages and changelog generation
Add husky config in `package.json` file.

[AST-177] Enable husky and pre-commit hook

---

.github/workflows/publish.yml
.github/workflows/pull-requests.yml
jest.config.js

Create tests and release version workflow on github actions
To improve release experience

ci(github-action): implement github actions flow for tests and publish new versions

---

.github/workflows/publish.yml

Fix release script
The script is not installing the dependencies

Fix release script

---

src/components/ButtonsGroup/ButtonsGroup.tsx
src/components/ButtonsGroup/__tests__/ButtonsGroup.test.tsx
src/components/ButtonsGroup/stories/ButtonsGroup.story.tsx

Fix buttons group items props
To resolve this issue #622 
- Test button props on buttons group item

fix(buttons-group): transfer buttons group props to items

---

ios/AstroNative.xcodeproj/project.pbxproj
ios/Podfile.lock
src/components/ControlsToggles/Slider.tsx
src/components/ControlsToggles/__tests__/Slider.test.tsx

Corrigir a tipagem do componente Slider do astro.
Para subir uma nova release do Astro.
1. Corrigir a tipagem do componente Slider do astro incluindo as props da comunidade;
2. Chamar a prop`onSlidingComplete` na função `handleSlindingComplete`;
3. Colocar um valor default para a prop `step` (step=1) e passar a prop step para o Slider da comunidade;
4. Fazer testes para a função `handleSlidingComplete`.
[CONFIA-535](https://produtomagnetis.atlassian.net/browse/CONFIA-535)

fix(slider): Slider component types [CONFIA-535]

---

CHANGELOG.md
package.json

- **slider:** feat(slider): extends slider component props ([#650](https://github.com/magnetis/astro-native/commit/69722d24d9708a95e3511be05a12424c454349c6))
- chore: bump version from v1.9.0 to v1.10.0 ([69722d2](https://github.com/magnetis/astro-native/commit/2f458fb33ae073533a8d0b8455204b38339e3dc7))

Release v1.10.0

---

src/components/ButtonsGroup/ButtonsGroup.tsx

Fixes ButtonsGroup to add `flexDirection` style to container.
Following the needs to optimize our components.
1. Start storybook with `yarn storybook`;
2. Run your preferred simulator;
4. In the storybook page, choose `Buttons Group` in `Buttons Group`;
5. See if `ActiveType`, `ActiveVariant`, `InactiveType` and `InactiveVariant` props are working correctly;
[CONFIA-678](https://produtomagnetis.atlassian.net/browse/CONFIA-678)
[CONFIA-678]: https://produtomagnetis.atlassian.net/browse/CONFIA-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ButtonsGroup): add flexDirection to container [CONFIA-678]

---

src/components/Inputs/MaskedInput.tsx
src/components/Inputs/__tests__/MaskedInput.test.tsx

Fix MaskedInput component to not show the keyboard when it is disabled;
To behave correctly.
Add a validation before focusing the component.
1. Run the storybook and your preferred emulator;
2. Choose the MaskedInput component;
3. Set the component as disabled;
4. Press it on your emulator and see it doesn't show the keyboard.
[CONFIA-992](https://produtomagnetis.atlassian.net/browse/CONFIA-992)
[CONFIA-992]: https://produtomagnetis.atlassian.net/browse/CONFIA-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(MaskedInput): fix masked input component [CONFIA-992]

---

package.json
yarn.lock

Remove concurrently in the astro-native@next branch because it's not used anymore.
ref: https://github.com/magnetis/astro-native/commit/99405cc977b65db2cefb2c6dc57301d804ccdf30

chore(deps): remove unused library concurrently [CONFIA-1089]

---

yarn.lock

Update package `@sideway/formula` from 3.0.0 to 3.0.1 in astro-native next.
To have an updated project.
[N/A]
1. Update modules using `yarn` and `pod install`;
2. Run the storybook using `yarn storybook`;
3. Run the project using `yarn start` and start your preferred emulator;
4. Check if it works properly using the storybook to change options.
[CONFIA-1201](https://produtomagnetis.atlassian.net/browse/CONFIA-1201)
[CONFIA-1201]: https://produtomagnetis.atlassian.net/browse/CONFIA-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(sideway/formula) update package sideway/formula from 3.0.0 to 3.0.1 in astro-native next [CONFIA-1201]

---

CHANGELOG.md
package.json

* **MaskedInput:** fix masked input component ([#705](https://github.com/magnetis/astro-native/issues/705)) ([f6ca3a1](https://github.com/magnetis/astro-native/commit/f6ca3a187bd7cfe998c30a5ca87d9b0bc555c56d))
* **slider:** Slider component types [CONFIA-535] ([#650](https://github.com/magnetis/astro-native/issues/650)) ([69722d2](https://github.com/magnetis/astro-native/commit/69722d24d9708a95e3511be05a12424c454349c6))
* **link:** allow use any color ([#719](https://github.com/magnetis/astro-native/issues/719)) ([581f901](https://github.com/magnetis/astro-native/commit/581f901e3ad6b935f88e8c4d6b8e17a643f7cb5a))
[CONFIA-535]: https://produtomagnetis.atlassian.net/browse/CONFIA-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release v1.11.0

---

yarn.lock

Upgrade library JSDom from 16.4.0 to 16.7.0 in astro native next
To reduce the risks of vulnerabilities and to have a more updated version.
[N/A]
[N/A]

chore: upgrade lib jsdom from 16.4.0 to 16.7.0 in astro-native next

---

package.json
src/components/Buttons/__tests__/BaseButton.test.tsx
src/components/Buttons/__tests__/Button.test.tsx
src/components/Buttons/__tests__/IconButton.test.tsx
src/components/Buttons/__tests__/utils.test.tsx
src/components/Buttons/utils.ts
src/components/Tabs/__tests__/TabsContainer.test.tsx
src/components/Tabs/stories/TabsContainer.story.tsx
yarn.lock

- bump @magnetis/astro-tokens from 0.0.8 to 0.0.10
- Update colors `solidBrightLightest` to `solidBrightWhite`
Update specs to satisfy [Breaking Change conditions](https://github.com/magnetis/astro-tokens/releases/tag/v0.0.10)
- Update package @magnetis/astro-tokens
- Replace all `solidBrightLightest` to `solidBrightWhite`
- Run yarn storybook and run the project in your preferred emulator;
- On the side bar, choose Button;
- Check if it's working correctly.
- On the side bar, choose Tabs
- Check if it's working correctly. 
CONFIA-1310

chore(deps): bump @magnetis/astro-tokens from 0.0.8 to 0.0.10

---

jest.config.js
src/components/Divider/Divider.tsx
src/components/Divider/__tests__/Divider.test.tsx
src/components/Divider/constants.ts
src/components/Divider/index.ts
src/components/Divider/stories/Divider.story.tsx
src/components/Divider/stories/index.ts
src/components/Divider/types.ts
src/index.ts
storybook/stories.ts

Create Divider component in astro-native-next
To follow our Design System, having our components gathered in one place that can be used in different projects.
1. Creating the divider component;
2. Create story to be manipulated in the storybook.
Storybook:
iOS:
https://github.com/magnetis/astro-native/assets/35939685/66f3e889-c246-49c0-af6f-adb3211fd063
Android:
1. Pull the branch and run `yarn start` and `yarn storybook`;
2. Run your preferred emulator;
3. In the storybook, choose the Divider option in the side bar menu;
4. Change the properties and see if it changes in the emulator. The type on the upper divider cannot be changed, it is just for comparison.
[CONFIA-1337](https://produtomagnetis.atlassian.net/browse/CONFIA-1337)
[CONFIA-1337]: …

feat(components): add divider component in astro-native-next [CONFIA-1337]

---

.github/CODEOWNERS
.github/mention-to-slack.yml
.github/workflows/request-review.yml

Add pull request review automation
To simplify code review process
Add github action to mention someone in slack when PR is created

chore(astro-native-next): add request review slack automation [CONFIA-1350]

---

.github/CODEOWNERS
.github/mention-to-slack.yml
.github/workflows/request-review.yml

Add pull request review automation
To simplify code review process
Add github action to mention someone in slack when PR is created

chore(astro-native-main): add request review slack automation [CONFIA-1350]

---

package.json
yarn.lock

- bump @magnetis/astro-tokens from 0.0.8 to 0.0.10
- Update package @magnetis/astro-tokens
- Run yarn storybook and run the project in your preferred emulator;
- On the side bar, choose Button;
- Check if it's working correctly.
- On the side bar, choose Tabs
- Check if it's working correctly.
CONFIA-1432

chore(deps): bump @magnetis/astro-tokens from 0.0.10 to 0.0.11
